In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings #  for avoid unwanted warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns',None) # to show maximum number of columns

In [3]:
data=pd.read_csv('Crime.csv')

In [4]:
data.head()

,Incident ID,Offence Code,CR Number,Dispatch Date / Time,NIBRS Code,Victims,Crime Name1,Crime Name2,Crime Name3,Police District Name,Block Address,City,State,Zip Code,Agency,Place,Sector,Beat,PRA,Address Number,Street Prefix,Street Name,Street Suffix,Street Type,Start_Date_Time,End_Date_Time,Latitude,Longitude,Police District Number,Location
0,201223224,2303,190002520,01/16/2019 03:51:46 PM,23C,1,Crime Against Property,Shoplifting,LARCENY - SHOPLIFTING,WHEATON,11100 BLK VEIRS MILL RD,SILVER SPRING,MD,20902.0,MCPD,Retail - Department/Discount Store,L,4L2,321.0,11100.0,NaN,VEIRS MILL,NaN,RD,01/16/2019 03:51:00 PM,NaN,39.037367,-77.051662,4D,"(39.0374, -77.0517)"
1,201224613,2006,190004310,01/27/2019 06:05:56 PM,200,1,Crime Against Property,Arson,ARSON - RESIDENTIAL,MONTGOMERY VILLAGE,400 BLK GIRARD ST,GAITHERSBURG,MD,20877.0,MCFM,Residence - Apartment/Condo,P,6P3,419.0,400.0,NaN,GIRARD,NaN,ST,01/27/2019 06:05:00 PM,NaN,39.146531,-77.184940,6D,"(39.1465, -77.1849)"
2,201267200,1103,190057412,11/28/2019 06:08:02 AM,11A,1,Crime Against Person,Forcible Rape,RAPE - STRONG-ARM,WHEATON,10900 BLK GEORGIA AVE,SILVER SPRING,MD,20902.0,MCPD,Residence - Apartment/Condo,L,4L2,323.0,10900.0,NaN,GEORGIA,NaN,AVE,11/28/2019 06:08:00 AM,NaN,39.034255,-77.049163,4D,"(39.0343, -77.0492)"
3,201230900,1399,190011960,03/15/2019 10:53:22 AM,13B,2,Crime Against Person,Simple Assault,ASSAULT - 2ND DEGREE,MONTGOMERY VILLAGE,700 BLK QUINCE ORCHARD BLV,GAITHERSBURG,MD,20878.0,GPD,Street - Residential,P,6P2,554.0,700.0,NaN,QUINCE ORCHARD,NaN,BLV,03/15/2019 10:50:00 AM,03/15/2019 10:55:00 AM,39.141812,-77.224489,6D,"(39.1418, -77.2245)"
4,201265312,1399,190055150,11/15/2019 03:31:20 PM,13B,1,Crime Against Person,Simple Assault,ASSAULT - 2ND DEGREE,MONTGOMERY VILLAGE,NaN,MONTGOMERY VILLAGE,MD,20886.0,MCPD,Street - Residential,R,6R1,505.0,NaN,NaN,MIDCOUNTY,NaN,HWY,11/15/2019 03:20:00 PM,NaN,39.159339,-77.198516,6D,"(39.1593, -77.1985)"

In [6]:
print('Total No Of ROWs =',data.shape[0])
print('Total No Of COLUMNs =',data.shape[1])

Total No Of ROWs = 225690
Total No Of COLUMNs = 30

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225690 entries, 0 to 225689
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Incident ID             225690 non-null  int64
 1   Offence Code            225690 non-null  object
 2   CR Number               225690 non-null  int64
 3   Dispatch Date / Time    156891 non-null  object
 4   NIBRS Code              225690 non-null  object
 5   Victims                 225690 non-null  int64
 6   Crime Name1             225549 non-null  object
 7   Crime Name2             225549 non-null  object
 8   Crime Name3             225549 non-null  object
 9   Police District Name    225690 non-null  object
 10  Block Address           205188 non-null  object
 11  City                    224633 non-null  object
 12  State                   225690 non-null  object
 13  Zip Code                222503 non-null  float64
 14  Agency                  225690 non-null  object
 15  Place                   225690 non-null  object
 16  Sector                  225631 non-null  object
 17  Beat                    225631 non-null  object
 18  PRA                     225649 non-null  object
 19  Address Number          205262 non-null  float64
 20  Street Prefix           9949 non-null    object
 21  Street Name             225690 non-null  object
 22  Street Suffix           4243 non-null    object
 23  Street Type             225376 non-null  object
 24  Start_Date_Time         225690 non-null  object
 25  End_Date_Time           109038 non-null  object
 26  Latitude                225690 non-null  float64
 27  Longitude               225690 non-null  float64
 28  Police District Number  225690 non-null  object
 29  Location                225690 non-null  object
dtypes: float64(4), int64(3), object(23)
memory usage: 51.7+ MB

In [10]:
data.isnull().sum()

Incident ID                    0
Offence Code                   0
CR Number                      0
Dispatch Date / Time       68799
NIBRS Code                     0
Victims                        0
Crime Name1                  141
Crime Name2                  141
Crime Name3                  141
Police District Name           0
Block Address              20502
City                        1057
State                          0
Zip Code                    3187
Agency                         0
Place                          0
Sector                        59
Beat                          59
PRA                           41
Address Number             20428
Street Prefix             215741
Street Name                    0
Street Suffix             221447
Street Type                  314
Start_Date_Time                0
End_Date_Time             116652
Latitude                       0
Longitude                      0
Police District Number         0
Location                       0
dtype: int64

In [11]:
a = round((data.isnull().mean()*100),2)
mssingcolumn=[]
missingdata=[]
missingnum=[]
for i in range(len(a)):
    if a.values[i] != 0:
        mssingcolumn.append(a.keys()[i])
for i in mssingcolumn:
    missingdata.append(round((data[i].isnull().mean()*100),2))
    missingnum.append(data[i].isnull().sum())
missing=pd.DataFrame({'column':mssingcolumn,'missing percent':missingdata,'missing num':missingnum}) 
missing

                  column  missing percent  missing num
0   Dispatch Date / Time            30.48        68799
1            Crime Name1             0.06          141
2            Crime Name2             0.06          141
3            Crime Name3             0.06          141
4          Block Address             9.08        20502
5                   City             0.47         1057
6               Zip Code             1.41         3187
7                 Sector             0.03           59
8                   Beat             0.03           59
9                    PRA             0.02           41
10        Address Number             9.05        20428
11         Street Prefix            95.59       215741
12         Street Suffix            98.12       221447
13           Street Type             0.14          314
14         End_Date_Time            51.69       116652

(39.0374, -77.0517)    3173
(39.1984, -77.2449)    1783
(39.0221, -77.1474)    1471
(39.1507, -77.2041)    1251
(39.1118, -77.2353)    1143
                       ...
(38.9805, -77.0633)       1
(38.9791, -77.1182)       1
(39.1484, -77.0517)       1
(39.1101, -77.2454)       1
(39.1975, -77.402)        1
Name: Location, Length: 23457, dtype: int64